server:
  port: 8080

csv:
  file-path: data.csv

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admin
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher