version: '3'

services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

  ksp-app:
    build:
      context: ../../..
      dockerfile: ./src/main/docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - spring_datasource_url=jdbc:postgresql://postgres:5432/admin
      - spring_batch_job_enabled=false

volumes:
  db-data:

